version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql2025
    hostname: sql2025
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Teste@123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"